-- Schema de la base de donnees de la securite sociale

-- Table: personne
CREATE TABLE public.personne (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom character varying(255),
    date_naissance date,
    sexe character varying(255),
    indicatif_pays character varying(255),
    num_telephone character varying(255),
    CONSTRAINT personne_pkey PRIMARY KEY (id)
);

-- Table: medecin (heritage de personne)
CREATE TABLE public.medecin (
    id bigint NOT NULL,
    matricule character varying(255),
    est_assure boolean,
    CONSTRAINT medecin_pkey PRIMARY KEY (id),
    CONSTRAINT fkr0053wn8500h0h9qu0hxkbqlj FOREIGN KEY (id) REFERENCES public.personne(id)
);

-- Table: generaliste (heritage de medecin)
CREATE TABLE public.generaliste (
    id bigint NOT NULL,
    CONSTRAINT generaliste_pkey PRIMARY KEY (id),
    CONSTRAINT fk2ojrm9brl80r1msn9yxskm7rx FOREIGN KEY (id) REFERENCES public.medecin(id)
);

-- Table: specialiste (heritage de medecin)
CREATE TABLE public.specialiste (
    id bigint NOT NULL,
    domaine_specialisation character varying(255),
    CONSTRAINT specialiste_pkey PRIMARY KEY (id),
    CONSTRAINT fkstog1kvv28t4ps64omartjci8 FOREIGN KEY (id) REFERENCES public.medecin(id)
);

-- Table: assure (heritage de personne)
CREATE TABLE public.assure (
    id bigint NOT NULL,
    id_assure character varying(255),
    profession character varying(255),
    groupe_sanguin character varying(255),
    statut_matrimonial character varying(255),
    date_inscription date,
    medecin_traitant_id bigint,
    CONSTRAINT assure_pkey PRIMARY KEY (id),
    CONSTRAINT uklys5euyxveg8tdls1qygvf6pa UNIQUE (id_assure),
    CONSTRAINT fk2c7mpvk12kgvpsbypgimb5f1t FOREIGN KEY (id) REFERENCES public.personne(id),
    CONSTRAINT fk214vt63ansrwe2t76klf7hivo FOREIGN KEY (medecin_traitant_id) REFERENCES public.generaliste(id)
);

-- Table: consultation
CREATE TABLE public.consultation (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date,
    assure_id bigint,
    generaliste_id bigint,
    CONSTRAINT consultation_pkey PRIMARY KEY (id),
    CONSTRAINT fkn867anou4bvdsa1e6g6i58udl FOREIGN KEY (assure_id) REFERENCES public.assure(id),
    CONSTRAINT fkf5jedl4jfcwyr2ubg0legfofo FOREIGN KEY (generaliste_id) REFERENCES public.generaliste(id)
);

-- Table: feuille_maladie
CREATE TABLE public.feuille_maladie (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_feuille character varying(255),
    montant_soin double precision,
    est_rembourse boolean,
    consultation_id bigint,
    CONSTRAINT feuille_maladie_pkey PRIMARY KEY (id),
    CONSTRAINT uklbrut9v0uj0coad28jxgvgr8q UNIQUE (id_feuille),
    CONSTRAINT ukkj7ouh1pa494ih7uxs0phlekl UNIQUE (consultation_id),
    CONSTRAINT fk6ow5lgm2hxlg85pduqc3f72qy FOREIGN KEY (consultation_id) REFERENCES public.consultation(id)
);

-- Table: remboursement
CREATE TABLE public.remboursement (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date_remboursement date,
    montant double precision,
    mode_paiement character varying(255),
    feuille_maladie_id bigint,
    CONSTRAINT remboursement_pkey PRIMARY KEY (id),
    CONSTRAINT ukqo1xp5oxrekcedhxxk83ex6o7 UNIQUE (feuille_maladie_id),
    CONSTRAINT fkq77ydb45nwxv23ydvhur20tjq FOREIGN KEY (feuille_maladie_id) REFERENCES public.feuille_maladie(id)
);

-- Table: prescription
CREATE TABLE public.prescription (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    consultation_id bigint,
    CONSTRAINT prescription_pkey PRIMARY KEY (id),
    CONSTRAINT fkbijh9r2m0km9ua4x4i4i53to6 FOREIGN KEY (consultation_id) REFERENCES public.consultation(id)
);

-- Table: prescription_consultation (heritage de prescription)
CREATE TABLE public.prescription_consultation (
    id bigint NOT NULL,
    matricule_medecin character varying(255),
    motif character varying(255),
    CONSTRAINT prescription_consultation_pkey PRIMARY KEY (id),
    CONSTRAINT fk1ib9w798bo7l6vgehamt2med0 FOREIGN KEY (id) REFERENCES public.prescription(id)
);

-- Table: prescription_medicament (heritage de prescription)
CREATE TABLE public.prescription_medicament (
    id bigint NOT NULL,
    medicament character varying(255),
    posologie character varying(255),
    CONSTRAINT prescription_medicament_pkey PRIMARY KEY (id),
    CONSTRAINT fktecl6l7kwgfq7x1vdh8fx4g0r FOREIGN KEY (id) REFERENCES public.prescription(id)
);
